[package]
name = "roblox-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.11", features = ["derive"] }
quote = "1.0.36"
syn = { version = "2.0.72", features = ["extra-traits", "full", "visit"] }

[dev-dependencies]
datatest = "0.8.0"
pretty_assertions = "1.4.0"
